name: Check Completeness 

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: all entries made
      run: bash ./.github/workflows/check-complete.sh
      
    - name: Install lizard
      run: pip install lizard

    - name: Limit complexity
      run: $HOME/.local/bin/lizard --exclude "./catch.hpp/*" --CCN 4
      
    - name: build
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o testchecker *.c*
      
    - name: run
      run: ./testchecker
      
    
