name: Check Completeness 

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: all entries made
      run: bash ./.github/workflows/check-complete.sh
      
    - name: Install jscpd
      run: sudo npm install -g jscpd

    - name: No Duplication beyond 3 lines
      run: jscpd . --min-lines 3 --min-tokens 48 --threshold 0
      
    - name: Install lizard
      run: pip install lizard

    - name: Limit complexity
      run: $HOME/.local/bin/lizard --exclude "./test/*" --CCN 3
      
    - name: build
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o testchecker *.c*
      
    - name: run
      run: ./testchecker
      
    
