name: Check Completeness 

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr

    - name: all entries made
      run: bash ./.github/workflows/check-complete.sh
      
    - name: Install lizard
      run: pip install lizard

    - name: Limit complexity
      run: $HOME/.local/bin/lizard --exclude "./catch.hpp/*" --CCN 4
      
    - name: build
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o testchecker *.c*
      
    - name: run
      run: ./testchecker
     
    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 1
